version: '3.8'
services:
  server:
    build: .
    restart: always
    ports:
      - "8181:8180"
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: occa_place
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - occasion-db:/var/lib/mysql
volumes:
  occasion-db: