pipeline {
    agent any

    tools {
        maven 'mvn'
    }

    environment {
        DOCKER_HUB_REPO = 'ilhamjalal123/occasion'
        DOCKER_IMAGE = 'occasion'
        DOCKER_COMPOSE_FILE = 'docker-compose.yml'
        DOCKER_CREDENTIALS_ID = 'docker-credentials-id'
        SONARQUBE = 'SonarQubeServer'
        SONARTOKEN = credentials('SonarToken')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Ilham-Jalal/ConstructionXpert-Services---Microservices-Frontend-.git'
            }
        }

        stage('Build and Test') {
            steps {
                dir('ConstructionXpertBackend') {
                    bat 'mvn clean install'
                    bat 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('ConstructionXpertBackend') {
                    withSonarQubeEnv(SONARQUBE) {
                        bat "mvn sonar:sonar -Dsonar.token=${SONARTOKEN}"
                    }
                }
            }
        }

                stage('Quality Gate Check') {
                    steps {
                        timeout(time: 5, unit: 'MINUTES') {
                            waitForQualityGate abortPipeline: true
                        }
                    }
                }

stage('Build Docker Images') {
            steps {
                script {
                    def services = ['config-server','eureka-server', 'api-gateway-service', 'project-service', 'resource-service', 'task-service', 'user-service']

                    dir('ConstructionXpertBackend') {
                        services.each { service ->
                            dir(service) {
                                bat "docker build -t constructionxpert-${service} ."
                            }
                        }
                    }
                }
            }
        }

     stage('Tag and Push Docker Images') {
            steps {
                script {
                    def services = ['config-server','eureka-server', 'api-gateway-service', 'project-service', 'resource-service', 'task-service', 'user-service']
                    docker.withRegistry("https://index.docker.io/v1/", 'docker-credentials-id') {
                        services.each { service ->
                            def imageName = "${DOCKER_HUB_REPO}:${service}"
                            bat """
                                docker tag constructionxpert-${service}:latest ${imageName}
                                docker push ${imageName}
                            """
                        }
                    }
                }
            }
        }
        stage('Run Docker Compose') {
            steps {
                script {
                    dir('ConstructionXpertBackend') {
                        bat 'docker-compose up -d'
                    }
                }
            }
        }
    }



    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
